fos_http_cache:
    cache_control:
        defaults:
            overwrite: true
        rules:
            # match all actions of a specific controller
            -
                match:
                    attributes: { _controller: ^AppBundle:Employees:.* }
                headers:
                    cache_control: { public: true, max_age: 604800, s_maxage: 604800 }
                    last_modified: "-1 hour"

            -
                match:
                    attributes: { _controller: ^AppBundle:PerformanceEvents:.* }
                    additional_cacheable_status: [400]
                headers:
                    cache_control: { public: true, max_age: 86400, s_maxage: 86400 }
                    last_modified: "-1 hour"

            -
                match:
                    attributes: { _controller: ^AppBundle:Performances:.* }
                    additional_cacheable_status: [400]
                headers:
                    cache_control: { public: true, max_age: 86400, s_maxage: 86400 }
                    last_modified: "-1 hour"

            -
                match:
                    attributes: { _controller: ^AppBundle:Posts:.* }
                    additional_cacheable_status: [400]
                headers:
                    cache_control: { public: true, max_age: 86400, s_maxage: 86400 }
                    last_modified: "-1 hour"

            # match everything to set defaults
            -
                match:
                    path: ^/
                headers:
                    overwrite: false
                    cache_control: { public: true, max_age: 86400, s_maxage: 86400 }
                    last_modified: "-1 hour"