admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
    resource: .
    type: sonata_admin

login:
  pattern:   /login
  defaults:  { _controller: AppBundle:Default:login }

login_check:
  pattern:   /login_check

logout:
  pattern: /logout
