NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: "%admin_dashboard_base_url%"

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: "%admin_dashboard_base_url%"

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

employees:
    type: rest
    resource: AppBundle\Controller\EmployeesController

performances:
    type: rest
    resource: AppBundle\Controller\PerformancesController

performance-events:
    type: rest
    resource: AppBundle\Controller\PerformanceEventsController
