# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.event_listener.serializer_subscriber:
        class: AppBundle\EventListener\SerializerSubscriber
        arguments: ["@sonata.media.controller.api.media"]
        tags:
            - { name: jms_serializer.event_subscriber }
