imports:
    - { resource: '@SonataTranslationBundle/Resources/config/config.yml'}

sonata_translation:
    locales: [ua, en]
    default_locale: ua
    # here enable the types you need
    gedmo:
        enabled: true
